name: Release after merged

on:
  pull_request:
    types: [closed]

jobs:
  release:

    runs-on: ubuntu-latest

    # Only if it is merged and contains a certain label.
    if: |
      github.event.pull_request.merged &&
      contains( github.event.pull_request.labels.*.name, 'eve: release after merged')

    steps:

    - name: Trigger lerna version
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_TOKEN_EVE }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'lerna-version.yml',
            ref: 'master',
          })
